spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  thymeleaf:
    cache: false
  application:
    name: freemall-search
  session:
    store-type: redis

  redis:
    host: 192.168.56.10
    port: 6379
server:
  port: 12000
